<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Net.Leksi.Pocota.ClientWpf</AssemblyName>
    <RootNamespace>Net.Leksi.Pocota.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\I18nConverter.Designer.cs">
      <DependentUpon>I18nConverter.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\I18nConverter.resx">
      <LastGenOutput>I18nConverter.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Net.Leksi.LifetimeObserver" Version="1.1.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PocotaClient\PocotaClient.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <ProjectReference Include="..\..\..\Localization\Localization\Localization.csproj" />
    <ProjectReference Include="..\..\..\WPF\WpfMarkupExtension\WpfMarkupExtension\WpfMarkupExtension.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <PackageReference Include="Net.Leksi.WpfMarkupExtension" Version="3.0.*" />
    <PackageReference Include="Net.Leksi.Localization" Version="1.0.*" />
  </ItemGroup>

</Project>
